config/routes.rb
Quizzes::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :quizzes do
    resources :questions
  end

  root to: 'quizzes#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :quiz

  validates_presence_of :title
  validates_uniqueness_of :title, scope: :quiz_id
  validates_numericality_of :position
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  has_many :questions

  validates_presence_of :name
  validates_uniqueness_of :name, :if => -> { name.present? }

  attr_accessible :name

  scope :ordered, order('id ASC')
  scope :approved, where(['id > ?', 3])
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :load_quiz

  # GET /questions
  def index
    @questions = @quiz.questions
  end

  # GET /questions/1
  def show
    @question = @quiz.questions.find(params[:id])
  end

  # GET /questions/new
  def new
    @question = @quiz.questions.build
  end

  # GET /questions/1/edit
  def edit
    @question = @quiz.questions.find(params[:id])
  end

  # POST /questions
  def create
    @question = @quiz.questions.build(params[:question])

    if @question.save
      redirect_to [@quiz, @question], notice: 'Question was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /questions/1
  def update
    @question = @quiz.questions.find(params[:id])

    if @question.update_attributes(params[:question])
      redirect_to [@quiz, @question], notice: 'Question was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /questions/1
  def destroy
    @question = @quiz.questions.find(params[:id])
    @question.destroy

    redirect_to quiz_questions_url(@quiz)
  end

  private

  def load_quiz
    @quiz = Quiz.find params[:quiz_id]
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
    @quiz = Quiz.find(params[:id])
  end

  # GET /quizzes/new
  # GET /quizzes/new.json
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
    @quiz = Quiz.find(params[:id])
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(params[:quiz])

    if @quiz.save
      redirect_to @quiz, notice: 'Quiz was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /quizzes/1
  # PUT /quizzes/1.json
  def update
    @quiz = Quiz.find(params[:id])

    if @quiz.update_attributes(params[:quiz])
      redirect_to @quiz, notice: 'Quiz was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz = Quiz.find(params[:id])
    @quiz.destroy

    redirect_to quizzes_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def errors_on(instance)
    return unless instance.errors.any?

    model = instance.class

    error_box_header = content_tag :h2 do
      t :header, count: instance.errors.count, model: model.model_name.human, scope: [model.i18n_scope, :errors, :template]
    end

    content_tag :div, id: 'error_explanation' do
      error_box_header +
      content_tag(:ul) do
        instance.errors.full_messages.map { |msg| content_tag :li, msg }.join('').html_safe
      end
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
  def title_for(quiz)
    content_tag :h1, quiz.name
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quizzes</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for([@quiz, @question]) do |f| %>
  <%= errors_on @question %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.number_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Редакция на въпрос</h1>

<%= render 'form' %>

<%= link_to 'Преглед', [@quiz, @question] %> |
<%= link_to 'Обратно', quiz_questions_path(@quiz) %>

app/views/questions/index.html.erb
<h1>Списък с въпроси в <%= link_to @quiz.name, @quiz %></h1>

<table>
  <tr>
    <th><%= Question.human_attribute_name :title %></th>
    <th><%= Question.human_attribute_name :position %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.title %></td>
    <td><%= question.position %></td>
    <td><%= link_to 'Преглед', quiz_question_path(@quiz, question) %></td>
    <td><%= link_to 'Редакция', edit_quiz_question_path(@quiz, question) %></td>
    <td><%= link_to 'Изтриване', quiz_question_path(@quiz, question), confirm: 'Моля, потвърдете изтриването на този елемент.', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Нов въпрос', new_quiz_question_path(@quiz) %>

app/views/questions/new.html.erb
<h1>Нов въпрос</h1>

<%= render 'form' %>

<%= link_to 'Обратно', quiz_questions_path(@quiz) %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= Question.human_attribute_name :title %>:</b>
  <%= @question.title %>
</p>

<p>
  <b><%= Question.human_attribute_name :position %>:</b>
  <%= @question.position %>
</p>


<%= link_to 'Редакция', edit_quiz_question_path(@quiz, @question) %> |
<%= link_to 'Обратно', quiz_questions_path(@quiz) %>

app/views/quizzes/_form.html.erb
<%= form_for(@quiz) do |f| %>
  <%= errors_on @quiz %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Редакция на въпросник</h1>

<%= render 'form' %>

<%= link_to 'Показване', @quiz %> |
<%= link_to 'Обратно', quizzes_path %>

app/views/quizzes/index.html.erb
<h1>Списък с въпросници</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Име</th>
    <th>Въпроси</th>
    <th colspan="3">Действия</th>
  </tr>

<% @quizzes.each do |quiz| %>
  <tr>
    <td><%= quiz.id %></td>
    <td><%= quiz.name %></td>
    <td><%= link_to pluralize(quiz.questions.size, 'въпрос',  'въпроса'), quiz_questions_path(quiz) %></td>
    <td><%= link_to 'Преглед', quiz %></td>
    <td><%= link_to 'Редактирай', edit_quiz_path(quiz) %></td>
    <td><%= link_to 'Изтриване', quiz, confirm: 'Моля, потвърдете изтриването на този елемент.', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Нов въпросник', new_quiz_path %>

app/views/quizzes/new.html.erb
<h1>Нов въпросник</h1>

<%= render 'form' %>

<%= link_to 'Обратно', quizzes_path %>

app/views/quizzes/show.html.erb
<%= title_for @quiz %>

<p id="notice"><%= notice %></p>

<p>
  <b><%= Quiz.human_attribute_name :name %>:</b>
  <%= @quiz.name %>
</p>


<%= link_to 'Редакция', edit_quiz_path(@quiz) %> |
<%= link_to 'Обратно', quizzes_path %>